import { uid } from "../utils";
import { localReport } from "./report";
import { scoreAssessment } from "./scoring";
import type { AnswerVal, AssessmentDraft } from "./types";

export function makeSampleAssessment(clientId: string): AssessmentDraft {
  const answers: Record<string, AnswerVal> = {
    name: "Alex",
    respondent: "carer",
    ageBand: "18-24",
    ndisStatus: "participant",
    disabilityWords: "Autism and ADHD. Shutdowns after busy shops. Needs a known person for morning care.",
    "whodas-length": "full",
    q1: 3,
    q2: 3,
    q3: 2,
    q4: 3,
    q5: 1,
    q6: 2,
    q7: 1,
    q8: 1,
    q9: 0,
    q10: 3,
    q11: 3,
    q12: 3,
    q13: 3,
    q14: 1,
    q15: 4,
    q16: 3,
    q17: 2,
    q18: 1,
    q19: 3,
    q21: 3,
    q22: 3,
    q23: 4,
    q24: 3,
    q25: 3,
    q26: 2,
    q29: 3,
    q30: 3,
    q31: 2,
    q32: 3,
    q33: 3,
    q36: 2,
    "h-interfere": 3,
    "h-days-unable": 9,
    "h-days-cut": 15,
    "need-selfCare-freq": 4,
    "need-selfCare-int": 3,
    "need-selfCare-note": "Dressing and medication prompts need a known worker every morning.",
    "need-community-freq": 3,
    "need-community-int": 3,
    "need-community-note": "Leaves the house only with 1:1 support. Crowds lead to a two-day shutdown.",
    "need-communication-freq": 2,
    "need-communication-int": 2,
    "need-domestic-freq": 3,
    "need-domestic-int": 3,
    "need-learning-freq": 3,
    "need-learning-int": 2,
    "need-generalTasks-freq": 4,
    "need-generalTasks-int": 3,
    "need-mental-freq": 3,
    "need-mental-int": 3,
    living: "family",
    "env-hours": "40plus",
    "env-location": "metro",
    "env-ifaway": "Morning routine stops. Meals are skipped. Cannot attend TAFE.",
    "perm-duration": "5plus",
    "perm-clinician": "yes",
    "perm-remedy": "no",
    "perm-fluctuate": "yes",
    "perm-evidence": ["gp", "allied", "school"],
    ndisFunctions: ["self-care", "social", "learning", "self-management"],
    "ms-why-ndis": "Health and education adjustments do not cover the morning routine or community access after shutdowns.",
  };
  const respondent = "carer";
  const score = scoreAssessment(respondent, answers);
  const id = uid("assess");
  const now = new Date().toISOString();
  const draft: AssessmentDraft = {
    id,
    clientId,
    createdAt: now,
    updatedAt: now,
    stepId: "review",
    respondent,
    answers,
    status: "complete",
    reportLocal: "",
    reportAi: "",
    score,
    unlocked: true,
  };
  draft.reportLocal = localReport(draft, score);
  return draft;
}
