/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as ArtRouteImport } from './routes/art'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as CarerRouteImport } from './routes/carer'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ClinicalRouteImport } from './routes/clinical'
import { Route as CodeOfConductRouteImport } from './routes/code-of-conduct'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as FluctuationRouteImport } from './routes/fluctuation'
import { Route as FunctionRouteImport } from './routes/function'
import { Route as FundingRouteImport } from './routes/funding'
import { Route as GetFilesRouteImport } from './routes/get-files'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PaidRouteImport } from './routes/paid'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RightsRouteImport } from './routes/rights'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as ScriptsRouteImport } from './routes/scripts'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ApiReadyRouteImport } from './routes/api/ready'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtRoute = ArtRouteImport.update({
  id: '/art',
  path: '/art',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const CarerRoute = CarerRouteImport.update({
  id: '/carer',
  path: '/carer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalRoute = ClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeOfConductRoute = CodeOfConductRouteImport.update({
  id: '/code-of-conduct',
  path: '/code-of-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const FluctuationRoute = FluctuationRouteImport.update({
  id: '/fluctuation',
  path: '/fluctuation',
  getParentRoute: () => rootRouteImport,
} as any)
const FunctionRoute = FunctionRouteImport.update({
  id: '/function',
  path: '/function',
  getParentRoute: () => rootRouteImport,
} as any)
const FundingRoute = FundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const GetFilesRoute = GetFilesRouteImport.update({
  id: '/get-files',
  path: '/get-files',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PaidRoute = PaidRouteImport.update({
  id: '/paid',
  path: '/paid',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RightsRoute = RightsRouteImport.update({
  id: '/rights',
  path: '/rights',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsRoute = ScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRoute
  '/art': typeof ArtRoute
  '/assessment': typeof AssessmentRoute
  '/budget': typeof BudgetRoute
  '/carer': typeof CarerRoute
  '/checklist': typeof ChecklistRoute
  '/clients': typeof ClientsRoute
  '/clinical': typeof ClinicalRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/companion': typeof CompanionRoute
  '/diary': typeof DiaryRoute
  '/flags': typeof FlagsRoute
  '/fluctuation': typeof FluctuationRoute
  '/function': typeof FunctionRoute
  '/funding': typeof FundingRoute
  '/get-files': typeof GetFilesRoute
  '/glossary': typeof GlossaryRoute
  '/goals': typeof GoalsRoute
  '/guide': typeof GuideRoute
  '/health': typeof HealthRoute
  '/impact': typeof ImpactRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/meeting': typeof MeetingRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/ops': typeof OpsRoute
  '/paid': typeof PaidRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/rights': typeof RightsRoute
  '/school': typeof SchoolRoute
  '/scripts': typeof ScriptsRoute
  '/wallet': typeof WalletRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRoute
  '/art': typeof ArtRoute
  '/assessment': typeof AssessmentRoute
  '/budget': typeof BudgetRoute
  '/carer': typeof CarerRoute
  '/checklist': typeof ChecklistRoute
  '/clients': typeof ClientsRoute
  '/clinical': typeof ClinicalRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/companion': typeof CompanionRoute
  '/diary': typeof DiaryRoute
  '/flags': typeof FlagsRoute
  '/fluctuation': typeof FluctuationRoute
  '/function': typeof FunctionRoute
  '/funding': typeof FundingRoute
  '/get-files': typeof GetFilesRoute
  '/glossary': typeof GlossaryRoute
  '/goals': typeof GoalsRoute
  '/guide': typeof GuideRoute
  '/health': typeof HealthRoute
  '/impact': typeof ImpactRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/meeting': typeof MeetingRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/ops': typeof OpsRoute
  '/paid': typeof PaidRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/rights': typeof RightsRoute
  '/school': typeof SchoolRoute
  '/scripts': typeof ScriptsRoute
  '/wallet': typeof WalletRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRoute
  '/art': typeof ArtRoute
  '/assessment': typeof AssessmentRoute
  '/budget': typeof BudgetRoute
  '/carer': typeof CarerRoute
  '/checklist': typeof ChecklistRoute
  '/clients': typeof ClientsRoute
  '/clinical': typeof ClinicalRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/companion': typeof CompanionRoute
  '/diary': typeof DiaryRoute
  '/flags': typeof FlagsRoute
  '/fluctuation': typeof FluctuationRoute
  '/function': typeof FunctionRoute
  '/funding': typeof FundingRoute
  '/get-files': typeof GetFilesRoute
  '/glossary': typeof GlossaryRoute
  '/goals': typeof GoalsRoute
  '/guide': typeof GuideRoute
  '/health': typeof HealthRoute
  '/impact': typeof ImpactRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/meeting': typeof MeetingRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/ops': typeof OpsRoute
  '/paid': typeof PaidRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/rights': typeof RightsRoute
  '/school': typeof SchoolRoute
  '/scripts': typeof ScriptsRoute
  '/wallet': typeof WalletRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointment'
    | '/art'
    | '/assessment'
    | '/budget'
    | '/carer'
    | '/checklist'
    | '/clients'
    | '/clinical'
    | '/code-of-conduct'
    | '/companion'
    | '/diary'
    | '/flags'
    | '/fluctuation'
    | '/function'
    | '/funding'
    | '/get-files'
    | '/glossary'
    | '/goals'
    | '/guide'
    | '/health'
    | '/impact'
    | '/language'
    | '/login'
    | '/meeting'
    | '/membership'
    | '/news'
    | '/ops'
    | '/paid'
    | '/practice'
    | '/privacy'
    | '/reports'
    | '/rights'
    | '/school'
    | '/scripts'
    | '/wallet'
    | '/api/ready'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointment'
    | '/art'
    | '/assessment'
    | '/budget'
    | '/carer'
    | '/checklist'
    | '/clients'
    | '/clinical'
    | '/code-of-conduct'
    | '/companion'
    | '/diary'
    | '/flags'
    | '/fluctuation'
    | '/function'
    | '/funding'
    | '/get-files'
    | '/glossary'
    | '/goals'
    | '/guide'
    | '/health'
    | '/impact'
    | '/language'
    | '/login'
    | '/meeting'
    | '/membership'
    | '/news'
    | '/ops'
    | '/paid'
    | '/practice'
    | '/privacy'
    | '/reports'
    | '/rights'
    | '/school'
    | '/scripts'
    | '/wallet'
    | '/api/ready'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/appointment'
    | '/art'
    | '/assessment'
    | '/budget'
    | '/carer'
    | '/checklist'
    | '/clients'
    | '/clinical'
    | '/code-of-conduct'
    | '/companion'
    | '/diary'
    | '/flags'
    | '/fluctuation'
    | '/function'
    | '/funding'
    | '/get-files'
    | '/glossary'
    | '/goals'
    | '/guide'
    | '/health'
    | '/impact'
    | '/language'
    | '/login'
    | '/meeting'
    | '/membership'
    | '/news'
    | '/ops'
    | '/paid'
    | '/practice'
    | '/privacy'
    | '/reports'
    | '/rights'
    | '/school'
    | '/scripts'
    | '/wallet'
    | '/api/ready'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentRoute: typeof AppointmentRoute
  ArtRoute: typeof ArtRoute
  AssessmentRoute: typeof AssessmentRoute
  BudgetRoute: typeof BudgetRoute
  CarerRoute: typeof CarerRoute
  ChecklistRoute: typeof ChecklistRoute
  ClientsRoute: typeof ClientsRoute
  ClinicalRoute: typeof ClinicalRoute
  CodeOfConductRoute: typeof CodeOfConductRoute
  CompanionRoute: typeof CompanionRoute
  DiaryRoute: typeof DiaryRoute
  FlagsRoute: typeof FlagsRoute
  FluctuationRoute: typeof FluctuationRoute
  FunctionRoute: typeof FunctionRoute
  FundingRoute: typeof FundingRoute
  GetFilesRoute: typeof GetFilesRoute
  GlossaryRoute: typeof GlossaryRoute
  GoalsRoute: typeof GoalsRoute
  GuideRoute: typeof GuideRoute
  HealthRoute: typeof HealthRoute
  ImpactRoute: typeof ImpactRoute
  LanguageRoute: typeof LanguageRoute
  LoginRoute: typeof LoginRoute
  MeetingRoute: typeof MeetingRoute
  MembershipRoute: typeof MembershipRoute
  NewsRoute: typeof NewsRoute
  OpsRoute: typeof OpsRoute
  PaidRoute: typeof PaidRoute
  PracticeRoute: typeof PracticeRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportsRoute: typeof ReportsRoute
  RightsRoute: typeof RightsRoute
  SchoolRoute: typeof SchoolRoute
  ScriptsRoute: typeof ScriptsRoute
  WalletRoute: typeof WalletRoute
  ApiReadyRoute: typeof ApiReadyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art': {
      id: '/art'
      path: '/art'
      fullPath: '/art'
      preLoaderRoute: typeof ArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carer': {
      id: '/carer'
      path: '/carer'
      fullPath: '/carer'
      preLoaderRoute: typeof CarerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical': {
      id: '/clinical'
      path: '/clinical'
      fullPath: '/clinical'
      preLoaderRoute: typeof ClinicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-of-conduct': {
      id: '/code-of-conduct'
      path: '/code-of-conduct'
      fullPath: '/code-of-conduct'
      preLoaderRoute: typeof CodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluctuation': {
      id: '/fluctuation'
      path: '/fluctuation'
      fullPath: '/fluctuation'
      preLoaderRoute: typeof FluctuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/function': {
      id: '/function'
      path: '/function'
      fullPath: '/function'
      preLoaderRoute: typeof FunctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funding': {
      id: '/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof FundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-files': {
      id: '/get-files'
      path: '/get-files'
      fullPath: '/get-files'
      preLoaderRoute: typeof GetFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paid': {
      id: '/paid'
      path: '/paid'
      fullPath: '/paid'
      preLoaderRoute: typeof PaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rights': {
      id: '/rights'
      path: '/rights'
      fullPath: '/rights'
      preLoaderRoute: typeof RightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts': {
      id: '/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof ScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentRoute: AppointmentRoute,
  ArtRoute: ArtRoute,
  AssessmentRoute: AssessmentRoute,
  BudgetRoute: BudgetRoute,
  CarerRoute: CarerRoute,
  ChecklistRoute: ChecklistRoute,
  ClientsRoute: ClientsRoute,
  ClinicalRoute: ClinicalRoute,
  CodeOfConductRoute: CodeOfConductRoute,
  CompanionRoute: CompanionRoute,
  DiaryRoute: DiaryRoute,
  FlagsRoute: FlagsRoute,
  FluctuationRoute: FluctuationRoute,
  FunctionRoute: FunctionRoute,
  FundingRoute: FundingRoute,
  GetFilesRoute: GetFilesRoute,
  GlossaryRoute: GlossaryRoute,
  GoalsRoute: GoalsRoute,
  GuideRoute: GuideRoute,
  HealthRoute: HealthRoute,
  ImpactRoute: ImpactRoute,
  LanguageRoute: LanguageRoute,
  LoginRoute: LoginRoute,
  MeetingRoute: MeetingRoute,
  MembershipRoute: MembershipRoute,
  NewsRoute: NewsRoute,
  OpsRoute: OpsRoute,
  PaidRoute: PaidRoute,
  PracticeRoute: PracticeRoute,
  PrivacyRoute: PrivacyRoute,
  ReportsRoute: ReportsRoute,
  RightsRoute: RightsRoute,
  SchoolRoute: SchoolRoute,
  ScriptsRoute: ScriptsRoute,
  WalletRoute: WalletRoute,
  ApiReadyRoute: ApiReadyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
